//! Overlay compositing: composite a PNG image onto a video using the `overlay` filter.
//!
//! This replaces the old ASS subtitle-based overlay pipeline. The PNG overlay
//! is generated by `reeln-overlay` and composited via ffmpeg's `overlay` filter
//! which is available in every ffmpeg/libav* build with zero additional dependencies.

use std::path::Path;

use crate::error::MediaError;

/// Options for compositing an overlay onto a video.
#[derive(Debug, Clone)]
pub struct CompositeOptions {
    /// X position of the overlay (default: 0).
    pub x: u32,
    /// Y position of the overlay (default: 0).
    pub y: u32,
    /// Start time in seconds (None = from beginning).
    pub start_time: Option<f64>,
    /// End time in seconds (None = until end).
    pub end_time: Option<f64>,
    /// Video codec for output.
    pub video_codec: String,
    /// CRF for encoding.
    pub crf: u32,
    /// Audio codec for output.
    pub audio_codec: String,
}

impl Default for CompositeOptions {
    fn default() -> Self {
        Self {
            x: 0,
            y: 0,
            start_time: None,
            end_time: None,
            video_codec: "libx264".to_string(),
            crf: 23,
            audio_codec: "aac".to_string(),
        }
    }
}

/// Result of a composite operation.
#[derive(Debug, Clone)]
pub struct CompositeResult {
    pub output: std::path::PathBuf,
    pub duration_secs: f64,
}

/// Composite a PNG overlay onto a video file using the native render pipeline.
///
/// Builds a `RenderPlan` with a `movie` filter-based `filter_complex` string
/// and delegates to the standard `render_native()` pipeline. Audio is preserved.
pub fn composite_overlay(
    video: &Path,
    overlay_png: &Path,
    output: &Path,
    opts: &CompositeOptions,
) -> Result<CompositeResult, MediaError> {
    if !video.exists() {
        return Err(MediaError::Render(format!(
            "video does not exist: {}",
            video.display()
        )));
    }
    if !overlay_png.exists() {
        return Err(MediaError::Render(format!(
            "overlay does not exist: {}",
            overlay_png.display()
        )));
    }

    // Build filter_complex: use movie source to load the PNG as a second input,
    // then overlay it onto the video. This avoids the complexity of managing
    // two buffer sources in the filter graph.
    let overlay_path_escaped = overlay_png
        .display()
        .to_string()
        .replace('\\', "\\\\")
        .replace(':', "\\:");

    let mut overlay_expr = format!("overlay={}:{}", opts.x, opts.y);
    match (opts.start_time, opts.end_time) {
        (Some(start), Some(end)) => {
            overlay_expr.push_str(&format!(":enable='between(t,{start},{end})'"));
        }
        (Some(start), None) => {
            overlay_expr.push_str(&format!(":enable='gte(t,{start})'"));
        }
        (None, Some(end)) => {
            overlay_expr.push_str(&format!(":enable='lte(t,{end})'"));
        }
        (None, None) => {}
    }

    let filter_complex =
        format!("movie={overlay_path_escaped}[_ovl];[0:v][_ovl]{overlay_expr},format=yuv420p");

    let plan = crate::RenderPlan {
        input: video.to_path_buf(),
        output: output.to_path_buf(),
        video_codec: opts.video_codec.clone(),
        crf: opts.crf,
        preset: Some("medium".to_string()),
        audio_codec: opts.audio_codec.clone(),
        audio_bitrate: None,
        filters: vec![],
        filter_complex: Some(filter_complex),
        audio_filter: None,
    };

    let result = crate::render::render_native(&plan)?;

    Ok(CompositeResult {
        output: result.output,
        duration_secs: result.duration_secs,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;

    fn create_test_video(path: &Path) {
        let status = Command::new("ffmpeg")
            .args([
                "-y",
                "-f",
                "lavfi",
                "-i",
                "testsrc=duration=2:size=160x120:rate=15",
                "-c:v",
                "libx264",
                "-pix_fmt",
                "yuv420p",
            ])
            .arg(path.as_os_str())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .expect("ffmpeg not found");
        assert!(status.success());
    }

    fn create_test_overlay(path: &Path, w: u32, h: u32) {
        let img = image::RgbaImage::from_fn(w, h, |x, _y| {
            if x < w / 2 {
                image::Rgba([255, 0, 0, 128]) // semi-transparent red
            } else {
                image::Rgba([0, 0, 0, 0]) // transparent
            }
        });
        img.save(path).unwrap();
    }

    #[test]
    fn test_composite_options_default() {
        let opts = CompositeOptions::default();
        assert_eq!(opts.x, 0);
        assert_eq!(opts.y, 0);
        assert!(opts.start_time.is_none());
        assert!(opts.end_time.is_none());
        assert_eq!(opts.video_codec, "libx264");
        assert_eq!(opts.crf, 23);
        assert_eq!(opts.audio_codec, "aac");
    }

    #[test]
    fn test_composite_options_clone_and_debug() {
        let opts = CompositeOptions {
            x: 10,
            y: 20,
            start_time: Some(1.0),
            end_time: Some(5.0),
            video_codec: "libx264".to_string(),
            crf: 18,
            audio_codec: "aac".to_string(),
        };
        let cloned = opts.clone();
        assert_eq!(cloned.x, 10);
        assert_eq!(cloned.crf, 18);
        let debug = format!("{opts:?}");
        assert!(debug.contains("CompositeOptions"));
    }

    #[test]
    fn test_composite_result_clone_and_debug() {
        let result = CompositeResult {
            output: PathBuf::from("/out.mp4"),
            duration_secs: 5.0,
        };
        let cloned = result.clone();
        assert_eq!(cloned.output, PathBuf::from("/out.mp4"));
        assert!((cloned.duration_secs - 5.0).abs() < f64::EPSILON);
        let debug = format!("{result:?}");
        assert!(debug.contains("CompositeResult"));
    }

    #[test]
    fn test_composite_nonexistent_video() {
        let opts = CompositeOptions::default();
        let result = composite_overlay(
            Path::new("/tmp/nonexistent_video.mp4"),
            Path::new("/tmp/overlay.png"),
            Path::new("/tmp/out.mp4"),
            &opts,
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_composite_nonexistent_overlay() {
        let dir = tempfile::tempdir().unwrap();
        let video = dir.path().join("test.mp4");
        create_test_video(&video);

        let opts = CompositeOptions::default();
        let result = composite_overlay(
            &video,
            Path::new("/tmp/nonexistent_overlay.png"),
            &dir.path().join("out.mp4"),
            &opts,
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_composite_basic() {
        let dir = tempfile::tempdir().unwrap();
        let video = dir.path().join("input.mp4");
        create_test_video(&video);

        let overlay = dir.path().join("overlay.png");
        create_test_overlay(&overlay, 80, 60);

        let output = dir.path().join("native_composited.mp4");
        let opts = CompositeOptions::default();
        let result = composite_overlay(&video, &overlay, &output, &opts).unwrap();

        assert!(output.exists());
        assert!(result.duration_secs > 1.0);
    }

    #[test]
    fn test_composite_with_position() {
        let dir = tempfile::tempdir().unwrap();
        let video = dir.path().join("input.mp4");
        create_test_video(&video);

        let overlay = dir.path().join("overlay.png");
        create_test_overlay(&overlay, 40, 30);

        let output = dir.path().join("native_positioned.mp4");
        let opts = CompositeOptions {
            x: 20,
            y: 10,
            ..Default::default()
        };
        let result = composite_overlay(&video, &overlay, &output, &opts).unwrap();
        assert!(output.exists());
        assert!(result.duration_secs > 1.0);
    }

    #[test]
    fn test_composite_with_timing() {
        let dir = tempfile::tempdir().unwrap();
        let video = dir.path().join("input.mp4");
        create_test_video(&video);

        let overlay = dir.path().join("overlay.png");
        create_test_overlay(&overlay, 40, 30);

        let output = dir.path().join("native_timed.mp4");
        let opts = CompositeOptions {
            start_time: Some(0.5),
            end_time: Some(1.5),
            ..Default::default()
        };
        let result = composite_overlay(&video, &overlay, &output, &opts).unwrap();
        assert!(output.exists());
        assert!(result.duration_secs > 1.0);
    }
}
